title: "Stoalaisuus"
description: "Kirjoituksia stoalaisuudesta ja työkaluja modernin tyhjyyden täyttämiseksi." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
author: "Janne K. Jääskeläinen"
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

email: "stoalaisuus@jannejaaskelainen.fi"
twitter_username: "JaaJanne"