title: "Stoalaisuus.fi"
description: "Antiikinaikaisia työkaluja modernin mielettömyyden hallintaan." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
author: "Janne K. Jääskeläinen"
show_downloads: false
theme: jekyll-theme-hacker
email: "stoalaisuus@jannejaaskelainen.fi"
twitter_username: "JaaJanne"

date_format: "%e.%m.%Y"

author:
  twitter: JaaJanne

kramdown:
  syntax_highlighter_opts:
    disable: true


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Yleiset